markdown: kramdown
permalink: pretty
title: Safely & Securely Producing Media
tagline: ....
description: ...
url: 'http://smallworldnews.github.io'
baseurl: /safelySecurelyProducingMedia
author:
  name: Small World News (smallworldnews.com)
  url: 'https://www.smallworldnews.com'
defaults:
  - scope:
      path: ''
    values:
      layout: default
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  enable_coderay: false
redcarpet:
  extensions:
    - tables
    - autolink
    - strikethrough
    - space_after_headers
    - with_toc_data
    - fenced_code_blocks
    - lax_spacing
    - smart
github:
  current_branch: master
  repository_url: 'https://github.com/smallworldnews/safelySecurelyProducingMedia'
gems:
  - jekyll-sitemap
  - jekyll-gist
safe: false
lsi: false
exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - '*.Rmd'
  - vendor
  - .travis.yml
username: smallworldnews
owner: smallworldnews
repo: safelySecurelyProducingMedia
